# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title detector
#'
#' @description Store a number of different compile-time \code{#define} values
#' and return them in a named character vector.
#'
#' @return A named character vector.
#' @useDynLib detector, .registration=TRUE
#' @importFrom Rcpp evalCpp
#' @export
detector <- function() {
    .Call(`_detector_detector`)
}

